### ISSUE TITLE
Pyflink docker image dose not exist.

### ISSUE THREAD

**Issue by xlamb1412** [morsapaes/pyflink-nlp#1]
There is no image pyflink/pyflink:1.11.2-scala_2.11.

**Comment by morsapaes** [comment]
I'm no longer maintaining this repo, @xlamb1412 (hence the note pointing people to the [Ververica-maintained fork](https://github.com/ververica/pyflink-nlp)). But I tried to reproduce it and only hit the image issue on an M1 Macbook; it came up just fine on Linux. What platform are you on?
